### PR TITLE
Add necessary deploy details

### PR DESCRIPTION
**Pull request by stvnrlly**

### CODE REVIEW

**Review by lauraGgit — COMMENTED** [review]
Would you not want to add a manifest-staging.yml

**Comment by stvnrlly** [comment]
@lauraGgit A staging-specific manifest is an option, but I was waiting until we had multiple environments to specify that. Happy to add it if you'd prefer that approach now.

**Comment by lauraGgit** [comment]
I'd rather have that now given that this will persist as the develop env.

**Comment by stvnrlly** [comment]
Done! I also created a new space and ported the app into it, in order to have everything line up properly.

One note: this is in our prototyping org. As soon as we move beyond prototyping, we'll want to move it into its own org with `staging` and `production` spaces, which will require a cloud.gov IAA.

**Review by lauraGgit — APPROVED** [review]
LGTM

**Pull request merged**
