### PR TITLE
Update django to close #22

### LINKED ISSUE #22: Update to the latest version of Django
This site isn't yet affected by the [vulnerability discussed here](https://www.djangoproject.com/weblog/2016/sep/26/security-releases/) because we don't have Google Analytics installed, but we'll want to update nonetheless.

### PR DESCRIPTION
**Pull request by lauraGgit**
Branch off of `field-sets`. Closes #22 

It's recommended in the release notes to create a new virtualenv when upgrading.

### CODE REVIEW

**Review by fureigh — CHANGES_REQUESTED** [review]
To update Django we only need the changes from `requirements.in` and `requirements.txt`, correct? If that's the case, please make a PR with just 52beca03bd3caf8e9a9996ac0b224c2ca17ef6dc and apply it to `develop`. I believe the other changes in this PR are already covered elsewhere.

**Comment by fureigh** [comment]
Thank you for the release notes note, P.S.

**Comment by lauraGgit** [comment]
Makes sense will open a new pr against develop

**Comment by lauraGgit** [comment]
Closed in favor of #45.

**Pull request closed without merging**
